### ISSUE TITLE
stopthecap - STOPTHECAP - Calling L2ECO.rebase through a different rebaser than L2ECOBridge will result in a mismatch in the linearInflationMultiplier parameters of these two contracts

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-ecoprotocol-judging#105]
stopthecap

medium

# STOPTHECAP - Calling L2ECO.rebase through a different rebaser than L2ECOBridge will result in a mismatch in the linearInflationMultiplier parameters of these two contracts

## Summary
Calling L2ECO.rebase through a rebaser other than L2ECOBridge will result in a mismatch in the linear inflation multiplier state variable of these two contracts.

## Vulnerability Detail
L2ECO contains a mapping of trusted "rebasers" that have the ability to call L2ECO.rebase, which changes its linearInflationMultiplier. The initial rebaser is set to the L2ECOBridge, as the default update flow involves the L1ECOBridge sending a cross-domain message to the L2ECOBridge to adjust the multiplier based on the L1 ECO token's past linear inflation multiplier.

However, since new rebasers can be added, there's a possibility that another address might be included as a rebaser. If a different rebaser calls L2ECO.rebase, the linearInflationMultiplier will deviate from L2ECOBridge.inflationMultiplier.

Consequently, deposits and withdrawals passing through L2ECOBridge will have an incorrect multiplier applied to these transfers.

## Impact
Deposits and withdrawals transacted through L2ECOBridge may have an incorrect linear inflation multiplier if a rebaser other than L2ECOBridge directly calls L2ECO.rebase.

## Code Snippet
https://github.com/sherlock-audit/2023-05-ecoprotocol/blob/b440f89234b806f672b9e9ad24cf70c409964db5/op-eco/contracts/token/L2ECO.sol#L253

## Tool used

Manual Review

## Recommendation
Ensure the linearInflationMultiplier value is always consistent across contracts. Instead of maintaining the value in two contracts, consider fetching it from a single contract when needed.

Rather than using an inflationMultiplier parameter on L2ECOBridge, call l2Eco.linearInflationMultiplier() directly.

**Comment by 0xffff11** [comment]
Escalate for 10 USDC.

Hello,

Issue #52 and #105 should not be marked as duplicates, as they pinpoint very distinct problems.

- Issue #52 - Front-running the Rebase Call
  - This issue highlights a front-running vulnerability where malicious users can exploit the difference in inflationMultiplier between the L1ECOBridge and L2ECOBridge contracts, particularly before the rebase call is executed. This discrepancy can be present immediately after the deployment and initialization of these bridges, and it's possible for users to deposit ECO tokens into the bridge and transfer them to L2 to take advantage of this differential. Essentially, this issue is about a specific timing attack based on the interval between deployment and rebase, allowing an adversary to manipulate the system.
- Issue #105 - Discrepancies due to Multiple Rebasers
  - While Issue #105 also concerns a difference in inflationMultipliers, the root cause is distinct from Issue #52. This issue exists due to the ability to add new rebasers to the L2ECO contract. If a different rebaser other than L2ECOBridge is permitted to call `L2ECO.rebase`, it could lead to a divergence between `linearInflationMultiplier` and `L2ECOBridge.inflationMultiplier`. The main issue here lies in the multiple rebasers' framework, creating an inconsistency that can persist even after the rebase call. Unlike Issue #52, this is not a one-time post-deployment problem, but a persistent issue linked to the multiple rebasers architecture, potentially leading to prolonged discrepancies in the inflationMultiplier.

Although both issues involve discrepancies between `L1ECOBridge` and `L2ECOBridge` inflation multipliers, they originate from separate points of vulnerability. Issue #52 arises from a specific timing attack exploiting the deployment and rebase process, whereas Issue #105 is a structural problem that arises from the ability to add multiple rebasers to the `L2ECO` contract.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC.
> 
> Hello,
> 
> Issue #52 and #105 should not be marked as duplicates, as they pinpoint very distinct problems.
> 
> - Issue #52 - Front-running the Rebase Call
>   - This issue highlights a front-running vulnerability where malicious users can exploit the difference in inflationMultiplier between the L1ECOBridge and L2ECOBridge contracts, particularly before the rebase call is executed. This discrepancy can be present immediately after the deployment and initialization of these bridges, and it's possible for users to deposit ECO tokens into the bridge and transfer them to L2 to take advantage of this differential. Essentially, this issue is about a specific timing attack based on the interval between deployment and rebase, allowing an adversary to manipulate the system.
> - Issue #105 - Discrepancies due to Multiple Rebasers
>   - While Issue #105 also concerns a difference in inflationMultipliers, the root cause is distinct from Issue #52. This issue exists due to the ability to add new rebasers to the L2ECO contract. If a different rebaser other than L2ECOBridge is permitted to call `L2ECO.rebase`, it could lead to a divergence between `linearInflationMultiplier` and `L2ECOBridge.inflationMultiplier`. The main issue here lies in the multiple rebasers' framework, creating an inconsistency that can persist even after the rebase call. Unlike Issue #52, this is not a one-time post-deployment problem, but a persistent issue linked to the multiple rebasers architecture, potentially leading to prolonged discrepancies in the inflationMultiplier.
> 
> Although both issues involve discrepancies between `L1ECOBridge` and `L2ECOBridge` inflation multipliers, they originate from separate points of vulnerability. Issue #52 arises from a specific timing attack exploiting the deployment and rebase process, whereas Issue #105 is a structural problem that arises from the ability to add multiple rebasers to the `L2ECO` contract. 

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by albertnbrown** [comment]
Can confirm that this would be a relevant issue. It is mitigated by the fact that there are no other rebaser contracts, but we saw this issue independently ourselves.

Addressed in this:
https://github.com/eco-association/op-eco/pull/40

**Comment by ctf-sec** [comment]
Emm

> However, since new rebasers can be added, there's a possibility that another address might be included as a rebaser. If a different rebaser calls L2ECO.rebase, the linearInflationMultiplier will deviate from L2ECOBridge.inflationMultiplier.

this would means the admin allows the rebaser to call L2ECO.rebase in the first place,

 the context onchain read me says:

> Q: Are the admins of the protocols your contracts integrate with (if any) TRUSTED or RESTRICTED?
There is a trusted admin contract given access to the L1ECOBridge contract as the upgrader. There is also trusted contracts in the Optimism (and Base) contract system that have certain privileges, but whatsons should have an understanding of these.

so the this would be a centralization risk

**Comment by hrishibhat** [comment]
Escalation rejected

Valid low
Updating the previous escalation decision. 
After further discussion with the Sponsor considering this issue as a valid low as adding new rebasers would require an upgrade and there is no issue with the code in its current form.

**Comment by sherlock-admin** [comment]
> Escalation rejected
> 
>Valid low
>Updating the previous escalation decision. 
>After further discussion with the Sponsor considering this issue as a valid low as adding new rebasers would require an upgrade and there is no issue with the code in its current form. 

    This issue's escalations have been accepted!

    Contestants' payouts and scores will be updated according to the changes made on this issue.
