### ISSUE TITLE
stopthecap - STOPTHECAP - L2ECO linearInflationMultiplier gets initialized to L1's INITIAL_INFLATION_MULTIPLIER, which is not necessarily the current inflation multiplier, allowing users to hypothetically bridge and frontrun a rebase in order to gain more L2 tokens

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-ecoprotocol-judging#106]
stopthecap

medium

# STOPTHECAP - L2ECO linearInflationMultiplier gets initialized to L1's INITIAL_INFLATION_MULTIPLIER, which is not necessarily the current inflation multiplier, allowing users to hypothetically bridge and frontrun a rebase in order to gain more L2 tokens

## Summary
The linearInflationMultiplier in L2ECO is initialized to the INITIAL_INFLATION_MULTIPLIER of L1 ECO, which may not necessarily reflect the current inflation multiplier on L1.

## Vulnerability Detail
The L2ECO initializer sets linearInflationMultiplier to INITIAL_INFLATION_MULTIPLIER. This is the same default value as the L1 ECO token: https://etherscan.io/address/0x8dBF9A4c99580fC7Fd4024ee08f3994420035727

However, since ECO is a rebasing token, this initial value may not necessarily correspond to the current inflation multiplier, which can be computed through IECO(l1Eco).getPastLinearInflation(block.number).

This indicates that the L2ECO initial value will always have an inflation multiplier which is less than or equal to L1's inflation multiplier.

If the L1 inflation multiplier is greater than its default value, users who bridge to L2 before a L2ECO.rebase is called will receive fewer tokens than they should.

## Impact
Users who bridge to L2 before a L2ECO.rebase is called will receive fewer tokens than they should if the L1 ECO inflation multiplier is different from its default value.

## Code Snippet
https://github.com/sherlock-audit/2023-05-ecoprotocol/blob/b440f89234b806f672b9e9ad24cf70c409964db5/op-eco/contracts/token/L2ECO.sol#L154

## Tool used

Manual Review

## Recommendation
Add a _linearInflationMultiplier function parameter to L2ECO.initialize so that a deployment script can correctly fetch L1's current inflation multiplier and set the default value of the L2ECO token.

Duplicate of #52

**Comment by 0xffff11** [comment]
Escalate for 10 USDC.

Hi,

Issue #52 and #106 should not be marked as duplicates, as they concern different vulnerabilities.

Issue #52 exposes a potential exploit where an actor can manipulate the time interval between the deployment and initialization of L1ECOBridge and L2ECOBridge contracts and the subsequent rebase call. This manipulation allows them to take advantage of a temporary differential in inflationMultiplier values between L1 and L2. This is fundamentally a timing attack that exploits the discrepancy in the inflationMultiplier values between the two bridge contracts in a narrow window post-deployment but prior to the first rebase call.

Issue #106, on the other hand, uncovers a problem in the initial setup of the `L2ECO` contract. Here, the issue lies in how the `linearInflationMultiplier` of the L2ECO contract is set to the `INITIAL_INFLATION_MULTIPLIER` of the L1 `ECO` contract during initialization. Due to the rebasing nature of ECO tokens, the L1 ECO's current/actual `inflationMultiplier` may not align with the L1 ECO multiplier set up at its deployment on Ethereum mainnet more than 6 months ago. The core issue here is not a timing exploit, but a problem with the initialization process that sets the `linearInflationMultiplier` of the L2ECO contract.

To put it plainly, Issue #52 is about exploiting a timing window for personal gain, whereas Issue #106 is concerned with an inherent problem in the initialization process of the L2 token. While it is true that both issues revolve around the potential discrepancies between the L1 and L2 inflation multipliers, their root causes, timing, and implications are different.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC.
> 
> Hi,
> 
> Issue #52 and #106 should not be marked as duplicates, as they concern different vulnerabilities.
> 
> Issue #52 exposes a potential exploit where an actor can manipulate the time interval between the deployment and initialization of L1ECOBridge and L2ECOBridge contracts and the subsequent rebase call. This manipulation allows them to take advantage of a temporary differential in inflationMultiplier values between L1 and L2. This is fundamentally a timing attack that exploits the discrepancy in the inflationMultiplier values between the two bridge contracts in a narrow window post-deployment but prior to the first rebase call.
> 
> Issue #106, on the other hand, uncovers a problem in the initial setup of the `L2ECO` contract. Here, the issue lies in how the `linearInflationMultiplier` of the L2ECO contract is set to the `INITIAL_INFLATION_MULTIPLIER` of the L1 `ECO` contract during initialization. Due to the rebasing nature of ECO tokens, the L1 ECO's current/actual `inflationMultiplier` may not align with the L1 ECO multiplier set up at its deployment on Ethereum mainnet more than 6 months ago. The core issue here is not a timing exploit, but a problem with the initialization process that sets the `linearInflationMultiplier` of the L2ECO contract.
> 
> To put it plainly, Issue #52 is about exploiting a timing window for personal gain, whereas Issue #106 is concerned with an inherent problem in the initialization process of the L2 token. While it is true that both issues revolve around the potential discrepancies between the L1 and L2 inflation multipliers, their root causes, timing, and implications are different.

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by JeffCX** [comment]
Emm this is a admin input validation.

https://docs.sherlock.xyz/audits/judging/judging#list-of-issue-categories-that-are-not-considered-valid

Admin Input/call validation:  Protocol admin is considered to be trusted in most cases, hence issues where
Admin incorrectly enters an input parameter. Example: Make sure interestPerMin > 1 ether as it is an important parameter.  This is not a valid issue.

**Comment by albertnbrown** [comment]
This is not an admin input validation because it is a constant on the contract.

However, it is not valid. If you look at the explanation on #52, you'll see that any mismatch between L2 and L1 inflation multiplier can never lead to a loss of funds or different amount of funds gained.

**Comment by hrishibhat** [comment]
Escalation rejected

Invalid issue
Maintaining the state as is based on sponsor comment.

**Comment by sherlock-admin** [comment]
> Escalation rejected
> 
> Invalid issue
> Maintaining the state as is based on sponsor comment. 
> 

    This issue's escalations have been rejected!

    Watsons who escalated this issue will have their escalation amount deducted from their next payout.
