### ISSUE TITLE
0xfuje - Too little `l2Gas` set on `depositERC20()` function could lead to lost deposited user funds

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-ecoprotocol-judging#136]
0xfuje

medium

# Too little `l2Gas` set on `depositERC20()` function could lead to lost deposited user funds

## Summary
Too little `l2Gas` set on `depositERC20()` function could lead to lost deposited user funds 

## Vulnerability Detail
The [depositERC20()](https://github.com/sherlock-audit/2023-05-ecoprotocol/blob/main/op-eco/contracts/bridge/L1ECOBridge.sol#L190) function in [L1ECOBridge.sol](https://github.com/sherlock-audit/2023-05-ecoprotocol/blob/main/op-eco/contracts/bridge/L1ECOBridge.sol) deposits ECO into the contract and for the deposit to be finalized [finalizeDeposit()](https://github.com/sherlock-audit/2023-05-ecoprotocol/blob/main/op-eco/contracts/bridge/L2ECOBridge.sol#L145) has to be called by the OP's L2CrossDomainMessenger contract that mints L2 Eco to the recipient. 

If you input less than 100_000 `l2Gas` to [depositERC20()](https://github.com/sherlock-audit/2023-05-ecoprotocol/blob/main/op-eco/contracts/bridge/L1ECOBridge.sol#L190) OP's [CanonicalTransactionChain](https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts/contracts/L1/rollup/CanonicalTransactionChain.sol) [(0x5e4e65926ba27467555eb562121fac00d24e9dd2)](https://etherscan.io/address/0x5e4e65926ba27467555eb562121fac00d24e9dd2#code) contract that handles cross-chain calls reverts with "Transaction gas limit too low to enqueue." saving the user from a failing transaction on L2.

However in a likely scenario where user provides more gas than the transaction gas limit but less than what is necessary to execute `finalizeDeposit()` on L2 user funds will be lost in [L1ECOBridge.sol](https://github.com/sherlock-audit/2023-05-ecoprotocol/blob/main/op-eco/contracts/bridge/L1ECOBridge.sol) since [finalizeDeposit()](https://github.com/sherlock-audit/2023-05-ecoprotocol/blob/main/op-eco/contracts/bridge/L2ECOBridge.sol#L145) can't execute and mint L2 ECO to the recipient.

Note: It's worth to note user funds could be recovered by a proxy update, however I still believe medium severity is justified because of the additional costs and complications of the potential recovery.

## Impact
User loses his deposited funds

## Code Snippet
[L1ECOBridge.sol - l2Gas in depositERC20()](https://github.com/sherlock-audit/2023-05-ecoprotocol/blob/main/op-eco/contracts/bridge/L1ECOBridge.sol#L194)
[L1ECOBridge.sol - sendCrossDomainMessage called with l2Gas in _initiateERC20Deposit()](https://github.com/sherlock-audit/2023-05-ecoprotocol/blob/main/op-eco/contracts/bridge/L1ECOBridge.sol#L350)

## Proof of Concept

I initialized a foundry repository for mainnet fork testing on Optimism and Ethereum to test vulnerabilities. You have to have foundry installed but the test setup is relatively simple:

1. Copy Eco Foundry Fork test repo and install dependencies:
```bash
git clone https://github.com/0xfuje/eco-audit-foundry-setup.git && cd eco-audit-foundry-setup && forge install
```

2. Change .env Mainnet fork variables to your Alchemy or Infura ID or (other RPC provider ID):
```bash
MAINNET_RPC_URL="https://eth-mainnet.g.alchemy.com/v2/YOUR-ALCHEMY-MAINNET-ID"
OPTIMISM_RPC_URL="https://opt-mainnet.g.alchemy.com/v2/YOUR-ALCHEMY-OPTIMISM-ID"
```

3. Mainnet test won't work because another vulnerability (onlyFromCrossDomain Denial of Service on mainnet). In order for the test to work comment out the second require statement from the `onlyFromCrossDomainAccount` modifier from `src/bridge/CrossDomainEnabledUpgradeable.sol` which mitigates the mentioned vulnerability. Please make sure to remove the comment after the test is finished in order for other tests to work.

```solidity
modifier onlyFromCrossDomainAccount(address _sourceDomainAccount) {
    require(
        msg.sender == address(getCrossDomainMessenger()),
        "OVM_XCHAIN: messenger contract unauthenticated"
    );

    require(
        getCrossDomainMessenger().xDomainMessageSender() ==
            _sourceDomainAccount,
        "OVM_XCHAIN: wrong sender of cross-domain message"
    );
    _;
}
```

3. Copy the following code into test/EcoTestSetup.t.sol:
```solidity
contract TestL2GasFail is EcoTestSetup {
    function testL2GasFail() external {
        // select ethereum mainnet fork
        vm.selectFork(mainnetFork);
        uint256 depositAmount = 10e18;

        uint32 gasReverts = 99_999;
        uint32 gasPasses = 100_000;

        vm.startPrank(alice);
        eco.approve(address(l1EcoBridge), depositAmount);

        // depositERC20 call reverts with any gas value below 100_000
        vm.expectRevert();
        l1EcoBridge.depositERC20(
            address(eco),
            address(l2Eco),
            depositAmount,
            gasReverts,
            NON_NULL_BYTES32
        );
        
        // but you can accidentally deposit just enough that you can execute depositERC20
        // but not enough to execute the finalizeDeposit call on L2
        l1EcoBridge.depositERC20(
            address(eco),
            address(l2Eco),
            depositAmount,
            gasPasses,
            NON_NULL_BYTES32
        );
        vm.stopPrank();

        // switch to optimism mainnet fork
        vm.selectFork(optimismFork);
        // set optimism gas price to realistic value
        uint256 gasPrice = 3;
        vm.txGasPrice(gasPrice);

        // simulate op cross domain messenger call to finalize deposit
        vm.prank(L2_OP_CROSS_DOMAIN_MESSENGER);
        // measure gas before and after to calculate total gas used in the finalizeDeposit call
        uint256 gasStart = gasleft();
        l2EcoBridge.finalizeDeposit(
            address(eco),
            address(l2Eco),
            alice,
            alice,
            depositAmount * INITIAL_INFLATION_MULTIPLIER,
            NON_NULL_BYTES32
        );
        uint256 gasEnd = gasleft();
        uint256 gasUsed = (gasStart - gasEnd) * gasPrice;

        emit log_uint(gasPasses);
        emit log_uint(gasUsed);
        // gas is not enough for execution, gas used is more than provided
        // this means finalizeDeposit wouldn't execute on mainnet and user loses his funds
        assertLt(gasPasses, gasUsed);
    }
}
```
4. Run the test 
```bash
forge test --match-test testL2GasFail -vvvv
```

## Tool used
Manual Review, Foundry, Mainnet Fork Tests

## Recommendation
Set a minimum `l2Gas` limit that makes sure that `finalizeDeposit()` is executed on L2 in normal circumstances. Alternatively the front-end can warn the user about the minimum recommended L2 Gas limit.

**Comment by 0xfuje** [comment]
Escalation for 1 USDC
The following submissions reported the same issue: [6](https://github.com/sherlock-audit/2023-05-ecoprotocol-judging/issues/6), [39](https://github.com/sherlock-audit/2023-05-ecoprotocol-judging/issues/39), [68](https://github.com/sherlock-audit/2023-05-ecoprotocol-judging/issues/68). I want to kindly ask for clarification and reconsideration primarily on my issue but I'm also curious why the others were excluded.

[Sherlock's FAQ on judging](https://docs.sherlock.xyz/audits/judging/judging) states below the: List of Issue categories that are considered valid: 
> **Out of Gas**: Issues that result in Out of Gas errors either by the malicious user filling up the arrays or there is a practical call flow that results in OOG can be considered a valid medium or in cases of blocking all user funds forever maybe a valid high.

I understand that the above mentioned other submissions fail to mention that any call below 100_000 l2Gas will simply revert and not cause any lost user funds (OP's CanonicalTransactionChain contract reverts: "Transaction gas limit too low to enqueue.") which could be an argument why they were excluded.

However as I stated in my submission any call to `depositERC20()` that is above 100_000 `l2Gas` but below the required gas to execute `finalizeDeposit` on L2 will fail. This would lead to lost user funds because there's no recovery method on the bridge contracts that would retrieve funds if finalizeDeposit would fail.

In my mainnet fork testing, I simulated the cost of `finalizeDeposit` assuming the gas price is 3: which would be 239_499 gas with the arguments given. Any l2Gas amount that is below 239_499 and above or equal to 100_000 would fail and lead to lost `amount` of ECO tokens.

**Comment by 0xfuje** [comment]
Escalate for 10 USDC
The following submissions reported the same issue: https://github.com/sherlock-audit/2023-05-ecoprotocol-judging/issues/6, https://github.com/sherlock-audit/2023-05-ecoprotocol-judging/issues/39, https://github.com/sherlock-audit/2023-05-ecoprotocol-judging/issues/68. I want to kindly ask for clarification and reconsideration primarily on my issue but I'm also curious why the others were excluded.

[Sherlock's FAQ on judging](https://docs.sherlock.xyz/audits/judging/judging) states below the: List of Issue categories that are considered valid:

> **Out of Gas**: Issues that result in Out of Gas errors either by the malicious user filling up the arrays or there is a practical call flow that results in OOG can be considered a valid medium or in cases of blocking all user funds forever maybe a valid high.

I understand that the above mentioned other submissions fail to mention that any call below 100_000 l2Gas will simply revert and not cause any lost user funds (OP's CanonicalTransactionChain contract reverts: "Transaction gas limit too low to enqueue.") which could be an argument why they were excluded.

However as I stated in my submission any call to depositERC20() that is above 100_000 l2Gas but below the required gas to execute finalizeDeposit on L2 will fail. This would lead to lost user funds because there's no recovery method on the bridge contracts that would retrieve funds if finalizeDeposit would fail.

In my mainnet fork testing, I simulated the cost of finalizeDeposit assuming the gas price is 3: which would be 239_499 gas with the arguments given. Any l2Gas amount that is below 239_499 and above or equal to 100_000 would fail and lead to lost amount of ECO tokens. It's certainly possible and even likely that without any restrictions and reverts that the user would put 239_499 > gas < 100_000 as a l2Gas input.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> The following submissions reported the same issue: https://github.com/sherlock-audit/2023-05-ecoprotocol-judging/issues/6, https://github.com/sherlock-audit/2023-05-ecoprotocol-judging/issues/39, https://github.com/sherlock-audit/2023-05-ecoprotocol-judging/issues/68. I want to kindly ask for clarification and reconsideration primarily on my issue but I'm also curious why the others were excluded.
> 
> [Sherlock's FAQ on judging](https://docs.sherlock.xyz/audits/judging/judging) states below the: List of Issue categories that are considered valid:
> 
> > **Out of Gas**: Issues that result in Out of Gas errors either by the malicious user filling up the arrays or there is a practical call flow that results in OOG can be considered a valid medium or in cases of blocking all user funds forever maybe a valid high.
> 
> I understand that the above mentioned other submissions fail to mention that any call below 100_000 l2Gas will simply revert and not cause any lost user funds (OP's CanonicalTransactionChain contract reverts: "Transaction gas limit too low to enqueue.") which could be an argument why they were excluded.
> 
> However as I stated in my submission any call to depositERC20() that is above 100_000 l2Gas but below the required gas to execute finalizeDeposit on L2 will fail. This would lead to lost user funds because there's no recovery method on the bridge contracts that would retrieve funds if finalizeDeposit would fail.
> 
> In my mainnet fork testing, I simulated the cost of finalizeDeposit assuming the gas price is 3: which would be 239_499 gas with the arguments given. Any l2Gas amount that is below 239_499 and above or equal to 100_000 would fail and lead to lost amount of ECO tokens. It's certainly possible and even likely that without any restrictions and reverts that the user would put 239_499 > gas < 100_000 as a l2Gas input.

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by JeffCX** [comment]
It is always difficult to set the exact amount of gas right, but I will bring this up for sponsor review!

**Comment by albertnbrown** [comment]
Yeah, user input on gas is up to the user and reverting is the correct functionality. On the side of the contract, in the secondary case you say, the funds are not lost if the L2 transaction reverts due to a bad gas limit. Optimism's L2 allows you to replay failed messages and you can do so with the higher gas limit.

I do not feel like this is legitimate, but the code you submitted is interesting, so I'll investigate the source of this 100,000 gas number.

**Comment by 0xffff11** [comment]
Interesting report. I believe sherlock does not reward wrong users input, but nevertheless, if @albertnbrown proves it, at least it should be added somewhere as a check or in the docs

**Comment by hrishibhat** [comment]
Escalation rejected

Valid low
This is user input error additionally there does not seem to be loss if funds as pointed by the sponsor.

**Comment by sherlock-admin** [comment]
> Escalation rejected
> 
> Valid low
> This is user input error additionally there does not seem to be loss if funds as pointed by the sponsor. 

    This issue's escalations have been rejected!

    Watsons who escalated this issue will have their escalation amount deducted from their next payout.
